name: Build and Deploy
on:
  # schedule:
  #   - cron: "0 8 * * *"

  workflow_dispatch:
    inputs:
      isDeploy:
        description: "Whether the build should be deployed?"
        type: boolean
        required: true
        default: false
      skipBinaries:
        description: "Skip building precompiled binaries?"
        type: boolean
        required: true
        default: false
      skipJava:
        description: "Skip building Java?"
        type: boolean
        required: true
        default: false
      skipNodejs:
        description: "Skip building Node.js?"
        type: boolean
        required: true
        default: false
      skipWasm:
        description: "Skip building WebAssembly?"
        type: boolean
        required: true
        default: false
      skipPython:
        description: "Skip building Python?"
        type: boolean
        required: true
        default: false
      skipRust:
        description: "Skip building Rust?"
        type: boolean
        required: true
        default: false
      skipExtensions:
        description: "Skip building extensions?"
        type: boolean
        required: true
        default: false
      isNightly:
        description: "Whether the build is a nightly build?"
        type: boolean
        required: true
        default: false
env:
  PIP_BREAK_SYSTEM_PACKAGES: 1

permissions:
  contents: read

jobs:
  get-nightly-version:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' || github.event.inputs.isNightly == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Update nightly version
        run: |
          python3 -m pip install packaging
          python3 update-nightly-build-version.py | grep "New Python dev version:" | awk -F'New Python dev version: ' '{print $2}' | sed 's/\.$//' > version.txt
          cat version.txt
        working-directory: scripts
      
      - name: Upload version
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: scripts/version.txt

  build-precompiled-bin-mac:
    if: ${{ github.event_name == 'schedule' || github.event.inputs.skipBinaries != 'true' }}
    uses: ./.github/workflows/mac-precompiled-bin-workflow.yml
    with:
      isNightly: ${{ github.event_name == 'schedule' || github.event.inputs.isNightly == 'true' }}
    secrets: inherit

  build-precompiled-bin-linux:
    if: ${{ github.event_name == 'schedule' || github.event.inputs.skipBinaries != 'true' }}
    uses: ./.github/workflows/linux-precompiled-bin-workflow.yml
    with:
      isNightly: ${{ github.event_name == 'schedule' || github.event.inputs.isNightly == 'true' }}
    secrets: inherit

  build-precompiled-bin-windows:
    if: ${{ github.event_name == 'schedule' || github.event.inputs.skipBinaries != 'true' }}
    uses: ./.github/workflows/windows-precompiled-bin-workflow.yml
    with:
      isNightly: ${{ github.event_name == 'schedule' || github.event.inputs.isNightly == 'true' }}
    secrets: inherit
