name: Build Mac Precompiled Binaries

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      isNightly:
        type: boolean
        required: true
        default: false
env:
  PIP_BREAK_SYSTEM_PACKAGES: 1

permissions:
  contents: read

jobs:
  build-precompiled-bin-universal:
    runs-on: self-hosted-mac-x64
    steps:
      - uses: actions/checkout@v4
      
      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          pip3 install packaging
          python3 update-nightly-build-version.py
        working-directory: scripts

      - name: Build universal precompiled binaries
        run: |
          make NUM_THREADS=$(sysctl -n hw.ncpu)
          make install
        env:
          MACOSX_DEPLOYMENT_TARGET: 11.0
          CMAKE_OSX_ARCHITECTURES: "x86_64;arm64"

      - name: Collect artifacts
        run: |
          mv install/include/gorgonzola.h .
          mv install/include/gorgonzola.hpp .
          mv install/lib/libgorgonzola.dylib .
          mv install/bin/gorgonzola .

      - name: Verify binary information
        run: |
          file -b gorgonzola
          otool -l gorgonzola | grep minos
          file -b libgorgonzola.dylib
          otool -l libgorgonzola.dylib | grep minos

      - name: Create tarball
        run: |
          tar -czvf libgorgonzola-osx-universal.tar.gz gorgonzola.h gorgonzola.hpp libgorgonzola.dylib
          tar -czvf gorgonzola_cli-osx-universal.tar.gz gorgonzola

      - uses: actions/upload-artifact@v4
        with:
          name: libgorgonzola-osx-universal
          path: libgorgonzola-osx-universal.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: gorgonzola_cli-osx-universal
          path: gorgonzola_cli-osx-universal.tar.gz
